### ISSUE TITLE
Multiline dropdown 

### ISSUE THREAD

**Issue by domainoverflow** [atk4/invoice#13]
Hi @ibelar,

Your add-on is great. I've managed to make it work by doing: 

-composer require atk4/ui:1.7.1
-composer require atk4/invoice:@dev
-my atk.version is 1.6.8

and I almost got to work, I was wondering, before I spend additional hours, is it possible to: 

-Make the multiline field a drop-down ( to choose Items by name and drop down )  ? 

I tried to override InvoiceItems to add something like ( $this->hasOne("item_id",[new ItemsCustom(), 'ui'=>['form'=>['DropDown]]])->addField('description') ; 

And tried to match it in the InvoiceMgr initiation. But no success. 

Is that possible ? 

I also get a warning on the error_log ( Undefined index: multiline at MultiLine:355 ). 

 Any help is appreciated,

Thanks for your time,

**Comment by ibelar** [comment]
If field, use to define your MultiLine model, has values or enum property set, then I believe it should be map as a dropdown component automatically.

You can see a sample of that in https://github.com/atk4/ui/blob/develop/demos/multiline-containsmany.php

In Account model, the field named  'type' uses 'values' property and will automatically be mapped to a Dropdown in MultiLine.

**Comment by domainoverflow** [comment]
Thank you @ibelar !  Got it now, fully working.  Thanks for this neat add-on and for your time.
