### ISSUE TITLE
question (not issue): How to intercept fields in in $headerGroup

### ISSUE THREAD

**Issue by domainoverflow** [atk4/invoice#15]
Hi @ibelar , Thanks in advance for your time. My question please, is this:

-How do I intercept ( event ) fields in the header group ? Ex: Client. 

What am I trying to do ? I am trying to pass the client_id to the multiline onchange event that happens in InvoiceMgr ( $ml->onLineChange([$this->invoiceModel, 'jsUpdateFields'], ['qty','rate'] ) -but only the line items are included.  I need the client_id in addition to the item_id to get the price ( certain client_ids have different pricing, so item_id is not enough ). So at SimpleTax I can use both client_id and item_id -my goal is to be able to query the price using both ids. 

Thanks for any help, really appreciated.
s

**Comment by ibelar** [comment]
When you are in SimpleTax::jsUpdateFields() method, the Invoice model is already loaded.
In order to get Client information, you could simply do $client = $this->ref('client_id')

````
public function jsUpdateFields($rows, $f)
    {

        if (!$this->getField('subtotal') || !$this->getField('tax') || !$this->getField('total')) {
            return;
        }

        $client = $this->ref('client_id');
        $disc = $client->get('discount')

       // rest of code here...
        return $resp;
    }
```
Hope this help!

**Comment by domainoverflow** [comment]
Hi @ibelar , thanks for your reply.  But the ID is in the drop down ( invoice header ) and not in the db yet .. - as the multi line item onchange event hasn't saved the invoice yet - the ID I'm looking for is in that drop down .. are you saying the form drop down ( invoice header ) should be there even if not saved in the db yet, the model holds that drop down current value  ? Sorry .. I'm having the hardest time debugging this. Thank you so much for any additional help,   PS: I tried using the debug and console .. and it allocates too much memory - the only way I could debug was to add a this_client = $this->ref('reseller_id') ; var_dump ($this_client) ; file_put_contents("stop.everything","now") ;   ( and stop.everything is read-only so it throws an exception and I can see the debug .. 

which is below - and I can't see the chosen drop down value. 

------------------------
 object(atk4\invoice\Model\ResellersBridge)#522 (2) { ["id"]=> NULL ["conditions"]=> array(1) { [0]=> array(2) { [0]=> string(2) "id" [1]=> object(atk4\dsql\Query_PgSQL)#543 (2) { ["R"]=> string(35) "select "reseller_id" from "invoice"" ["mode"]=> string(6) "select" } } } } {"success":false,"message":"\n
\n
\n
\n
\n
\n
ErrorException: file_put_contents(stop.everything): failed to open stream: Permission denied<\/div>\n<\/div><\/div><\/div>\n <\/div>\n<\/div>"}

**Comment by ibelar** [comment]
You are right, Invoice should be saved before in order to get client reference. 
You would need to modify InvoiceMgr to your need, i.e. save Invoice into db prior to save item in it.
 
Other way might be to put an onChange event handler into client_id dropdown, when dropdown change, save it's value id, in session maybe, and use it for calculating new invoice item.

```
            $headerGroup->getField('client_id')->onChange(function($id) {
               // $_GET['client_id'] and save into session.
            }, ['args' => ['client_id' => (new jQuery())->val()]]);
```

**Comment by domainoverflow** [comment]
Thank You @ibelar - that's precisely what I needed.  Later, I will give back by documenting the full solution here and close the question. Thank you really !

**Comment by domainoverflow** [comment]
@ibelar , Please, how would I capture the value without having the alert popping up ? I am trying to understand the seed approach. thanks again !!

**Comment by domainoverflow** [comment]
I had an additional return. thanks !
