### ISSUE TITLE
Call to undefined method atk4\ui\Grid::addAction()

### ISSUE THREAD

**Issue by domainoverflow** [atk4/invoice#18]
Hi,

After the latest release, the invoice got broken, I was wondering how to fix it :-(

Call to undefined method atk4\ui\Grid::addAction() 
The error is at /vendor/atk4/invoice/src/Invoice.php 
$g->addAction(['icon'=>'dollar sign'] .............  ( @  displayInvoices() ).

Please, suggestions ? Alternative methods ?

thanks for your help !
s

**Comment by DarkSide666** [comment]
Looks like you're using some old code. Please pull latest changes from dev-develop branch.

Recently I fixed bunch of compatibility issues (https://github.com/atk4/invoice/commit/166ae5c6b88e3c0d86b3ec462a7b8b1c9992f2dc), but there still is at least one issue with "Pay Invoice" action. @ibelar will take a look at that when he get time.

**Comment by DarkSide666** [comment]
More issues was fixed in https://github.com/atk4/invoice/commit/4b788398ca26364cb7754d605cfbfcd43ceb4b9e
